# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

user = User.create!(email: "sennacy@cats.com", password: "111111")
user.notebooks.create!(title: "Workout tips")
user.notebooks.first.notes.create!(title: "Tail workout", body: "1) Stretch tail left ~ 3 minutes
2) Stretch tail rigth ~ 3 minutes 3) Stretch  tail up ~ 5 minutes")
user.notebooks.first.notes.create!(title: "Downward Facing Cat", body: "Downward Cat is used in most yoga practices and it stretches and strengthens the entire body. I always say, “a down cat a day keeps the doctor away.” How to do it: Come on to all fours with your wrists under your shoulders and knees under your hips. Tuck under your toes and lift your hips up off the floor as you draw them up at back towards your heels. Keep your knees slightly bent if your hamstrings are tight, otherwise try and straighten out your legs while keeping your hips back. Walk your hands forward to give yourself more length if you need to. Press firmly through your palms and rotate the inner elbows towards each other. Hollow out the abdominals and keep engaging your legs to keep the torso moving back towards the thighs. Hold for 5-8 breaths before dropping back to hands and knees to rest.")

user.notebooks.first.notes.create!(title: "Cat-Cow Pose", body: "Cat-Cow Pose teaches us how to balance on our hands while using the entire body to support us. It is a great way to strengthen the abdominals, and learn to use the breath to help us stay in a challenging pose. How to do it: From all fours, tuck under your toes and lift your legs up off the mat. Slide your heels back enough until you feel you are one straight line of energy from your head to your feet. Engage the lower abdominals, draw the shoulders down and away from the ears, pull your ribs together and breathe deeply for 8-10 breaths.")

user.notebooks.first.notes.create!(title: "Dolphin", body:'How to do it: Chant "bye-bye batwings"! Begin on your hands and knees, then lower your elbows to the floor, shoulder-distance apart. Interlace fingers, tuck your toes, and press hips up to create a long line between elbows and sitting bones (aka your butt). Slowly squeeze your upper arms inward to work biceps, triceps, and shoulders. Breathe and repeat.')
user.notebooks.first.notes.create!(title: "Boat Pose", body:'How to do it: Celeb yogini loves this move! Sit up high and straight, hands beneath your knees. Slowly tighten your abs and lift your feet off the floor, knees bent, with your legs at a 45-degree angle. If this feels easy, straighten your legs and arms. Breathe and slowly lower.')
user.notebooks.first.notes.create!(title: "Downward Dog Split Pose", body:'How to do it: Begin on hands and knees. Take a big breath out and push into Downward Dog by straightening legs and lifting your hips and butt in the air. Relax head between straightened arms. Exhale and lift one leg as high as you can into the air, flexing foot. Repeat on other side.')
user.notebooks.first.notes.create!(title: "Cow Pose", body:'How to do it: This move looks relaxing but is one of the toughest hip strengtheners and openers. Start on your hands and knees, and slide your right leg back to cross over your left leg. Gradually sit back between your heels, using a rolled up towel or block if you can’t sit on the ground. Hold as long as you feel comfortable, then switch legs and repeat.')
user.notebooks.first.notes.create!(title: "Side Plank Pose", body:'How to do it: From plank position, press your right hand into a mat and turn your body so your weight is on the outer edge of your right foot. Brace your core and keep your arms elevated over your head. Option to bend your leg and place it behind you for support, or, if you’re super fit, to rock a few mid-air crunches like our model Jillian Michaels!')

user.notebooks.first.notes.create!(title: "Tail workout2", body: "1) Stretch tail left ~ 3 minutes
2) Stretch tail rigth ~ 3 minutes 3) Stretch  tail up ~ 5 minutes")
user.notebooks.first.notes.create!(title: "Downward Facing Cat2", body: "Downward Cat is used in most yoga practices and it stretches and strengthens the entire body. I always say, “a down cat a day keeps the doctor away.” How to do it: Come on to all fours with your wrists under your shoulders and knees under your hips. Tuck under your toes and lift your hips up off the floor as you draw them up at back towards your heels. Keep your knees slightly bent if your hamstrings are tight, otherwise try and straighten out your legs while keeping your hips back. Walk your hands forward to give yourself more length if you need to. Press firmly through your palms and rotate the inner elbows towards each other. Hollow out the abdominals and keep engaging your legs to keep the torso moving back towards the thighs. Hold for 5-8 breaths before dropping back to hands and knees to rest.")

user.notebooks.first.notes.create!(title: "Cat-Cow Pose2", body: "Cat-Cow Pose teaches us how to balance on our hands while using the entire body to support us. It is a great way to strengthen the abdominals, and learn to use the breath to help us stay in a challenging pose. How to do it: From all fours, tuck under your toes and lift your legs up off the mat. Slide your heels back enough until you feel you are one straight line of energy from your head to your feet. Engage the lower abdominals, draw the shoulders down and away from the ears, pull your ribs together and breathe deeply for 8-10 breaths.")

user.notebooks.first.notes.create!(title: "Dolphin2", body:'How to do it: Chant "bye-bye batwings"! Begin on your hands and knees, then lower your elbows to the floor, shoulder-distance apart. Interlace fingers, tuck your toes, and press hips up to create a long line between elbows and sitting bones (aka your butt). Slowly squeeze your upper arms inward to work biceps, triceps, and shoulders. Breathe and repeat.')
user.notebooks.first.notes.create!(title: "Boat Pose2", body:'How to do it: Celeb yogini loves this move! Sit up high and straight, hands beneath your knees. Slowly tighten your abs and lift your feet off the floor, knees bent, with your legs at a 45-degree angle. If this feels easy, straighten your legs and arms. Breathe and slowly lower.')
user.notebooks.first.notes.create!(title: "Downward Dog Split Pose2", body:'How to do it: Begin on hands and knees. Take a big breath out and push into Downward Dog by straightening legs and lifting your hips and butt in the air. Relax head between straightened arms. Exhale and lift one leg as high as you can into the air, flexing foot. Repeat on other side.')
user.notebooks.first.notes.create!(title: "Cow Pose2", body:'How to do it: This move looks relaxing but is one of the toughest hip strengtheners and openers. Start on your hands and knees, and slide your right leg back to cross over your left leg. Gradually sit back between your heels, using a rolled up towel or block if you can’t sit on the ground. Hold as long as you feel comfortable, then switch legs and repeat.')
user.notebooks.first.notes.create!(title: "Side Plank Pose2", body:'How to do it: From plank position, press your right hand into a mat and turn your body so your weight is on the outer edge of your right foot. Brace your core and keep your arms elevated over your head. Option to bend your leg and place it behind you for support, or, if you’re super fit, to rock a few mid-air crunches like our model Jillian Michaels!')
