# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

user = User.create!(email: "sennacy@cats.com", password: "111111")
user.notebooks.create!(title: "Workout tips")
user.notebooks.first.notes.create!(title: "Tail workout", body: "1) Stretch tail left ~ 3 minutes
2) Stretch tail rigth ~ 3 minutes 3) Stretch  tail up ~ 5 minutes")
user.notebooks.first.notes.create!(title: "Downward Facing Cat", body: "Downward Cat is used in most yoga practices and it stretches and strengthens the entire body. I always say, “a down cat a day keeps the doctor away.” How to do it: Come on to all fours with your wrists under your shoulders and knees under your hips. Tuck under your toes and lift your hips up off the floor as you draw them up at back towards your heels. Keep your knees slightly bent if your hamstrings are tight, otherwise try and straighten out your legs while keeping your hips back. Walk your hands forward to give yourself more length if you need to. Press firmly through your palms and rotate the inner elbows towards each other. Hollow out the abdominals and keep engaging your legs to keep the torso moving back towards the thighs. Hold for 5-8 breaths before dropping back to hands and knees to rest.")

user.notebooks.first.notes.create!(title: "Cat-Cow Pose", body: "Cat-Cow Pose teaches us how to balance on our hands while using the entire body to support us. It is a great way to strengthen the abdominals, and learn to use the breath to help us stay in a challenging pose. How to do it: From all fours, tuck under your toes and lift your legs up off the mat. Slide your heels back enough until you feel you are one straight line of energy from your head to your feet. Engage the lower abdominals, draw the shoulders down and away from the ears, pull your ribs together and breathe deeply for 8-10 breaths.")

user.notebooks.first.notes.create!(title: "Dolphin", body:'How to do it: Chant "bye-bye batwings"! Begin on your hands and knees, then lower your elbows to the floor, shoulder-distance apart. Interlace fingers, tuck your toes, and press hips up to create a long line between elbows and sitting bones (aka your butt). Slowly squeeze your upper arms inward to work biceps, triceps, and shoulders. Breathe and repeat.')

user.notebooks.first.notes.create!(title: "Boat Pose", body:'How to do it: Celeb yogini loves this move! Sit up high and straight, hands beneath your knees. Slowly tighten your abs and lift your feet off the floor, knees bent, with your legs at a 45-degree angle. If this feels easy, straighten your legs and arms. Breathe and slowly lower.')

user.notebooks.first.notes.create!(title: "Downward Dog Split Pose", body:'How to do it: Begin on hands and knees. Take a big breath out and push into Downward Dog by straightening legs and lifting your hips and butt in the air. Relax head between straightened arms. Exhale and lift one leg as high as you can into the air, flexing foot. Repeat on other side.')

user.notebooks.first.notes.create!(title: "Cow Pose", body:'How to do it: This move looks relaxing but is one of the toughest hip strengtheners and openers. Start on your hands and knees, and slide your right leg back to cross over your left leg. Gradually sit back between your heels, using a rolled up towel or block if you can’t sit on the ground. Hold as long as you feel comfortable, then switch legs and repeat.')

user.notebooks.first.notes.create!(title: "Side Plank Pose", body:'How to do it: From plank position, press your right hand into a mat and turn your body so your weight is on the outer edge of your right foot. Brace your core and keep your arms elevated over your head. Option to bend your leg and place it behind you for support, or, if you’re super fit, to rock a few mid-air crunches like our model Jillian Michaels!')

user.notebooks.first.notes.create!(title: "Tail workout2", body: "1) Stretch tail left ~ 3 minutes
2) Stretch tail rigth ~ 3 minutes 3) Stretch  tail up ~ 5 minutes")
user.notebooks.first.notes.create!(title: "Downward Facing Cat2", body: "Downward Cat is used in most yoga practices and it stretches and strengthens the entire body. I always say, “a down cat a day keeps the doctor away.” How to do it: Come on to all fours with your wrists under your shoulders and knees under your hips. Tuck under your toes and lift your hips up off the floor as you draw them up at back towards your heels. Keep your knees slightly bent if your hamstrings are tight, otherwise try and straighten out your legs while keeping your hips back. Walk your hands forward to give yourself more length if you need to. Press firmly through your palms and rotate the inner elbows towards each other. Hollow out the abdominals and keep engaging your legs to keep the torso moving back towards the thighs. Hold for 5-8 breaths before dropping back to hands and knees to rest.")

user.notebooks.first.notes.create!(title: "Cat-Cow Pose2", body: "Cat-Cow Pose teaches us how to balance on our hands while using the entire body to support us. It is a great way to strengthen the abdominals, and learn to use the breath to help us stay in a challenging pose. How to do it: From all fours, tuck under your toes and lift your legs up off the mat. Slide your heels back enough until you feel you are one straight line of energy from your head to your feet. Engage the lower abdominals, draw the shoulders down and away from the ears, pull your ribs together and breathe deeply for 8-10 breaths.")

user.notebooks.first.notes.create!(title: "Dolphin2", body:'How to do it: Chant "bye-bye batwings"! Begin on your hands and knees, then lower your elbows to the floor, shoulder-distance apart. Interlace fingers, tuck your toes, and press hips up to create a long line between elbows and sitting bones (aka your butt). Slowly squeeze your upper arms inward to work biceps, triceps, and shoulders. Breathe and repeat.')
user.notebooks.first.notes.create!(title: "Boat Pose2", body:'How to do it: Celeb yogini loves this move! Sit up high and straight, hands beneath your knees. Slowly tighten your abs and lift your feet off the floor, knees bent, with your legs at a 45-degree angle. If this feels easy, straighten your legs and arms. Breathe and slowly lower.')
user.notebooks.first.notes.create!(title: "Downward Dog Split Pose2", body:'How to do it: Begin on hands and knees. Take a big breath out and push into Downward Dog by straightening legs and lifting your hips and butt in the air. Relax head between straightened arms. Exhale and lift one leg as high as you can into the air, flexing foot. Repeat on other side.')
user.notebooks.first.notes.create!(title: "Cow Pose2", body:'How to do it: This move looks relaxing but is one of the toughest hip strengtheners and openers. Start on your hands and knees, and slide your right leg back to cross over your left leg. Gradually sit back between your heels, using a rolled up towel or block if you can’t sit on the ground. Hold as long as you feel comfortable, then switch legs and repeat.')
user.notebooks.first.notes.create!(title: "Side Plank Pose2", body:'How to do it: From plank position, press your right hand into a mat and turn your body so your weight is on the outer edge of your right foot. Brace your core and keep your arms elevated over your head. Option to bend your leg and place it behind you for support, or, if you’re super fit, to rock a few mid-air crunches like our model Jillian Michaels!')


user.notebooks.create!(title: "Misc")
user.notebooks.find(2).create!(title: "Scenacy's birthday", body: "August 10! Gift??\r\n - iphone watch\r\n - puppy\r\n - new microvave??? \r\n\r\n Order cake: Red Velvet Westside Bakery Phone:(212) 350-4144")

user.notebooks.find(2).create!(title: "Russian Visa", body: "Travel to Russia requires an entry visa. The Consular Division of the Embassy issues different categories of visas to Russia based upon the purpose of the trip and the duration of stay in Russia. \r\n\r\n The following documents should be submitted in order to obtain a visa according to its category: \r\n\r\n 1. Completed visa application signed by the Applicant only. Incomplete visa application forms shall not be processed. \r\n\r\n  Application available online at http://visa.kdmid.ru \r\n\r\n All questions in the application form should be answered. If a question is not applicable to the applicant, he should put “N/A”. \r\n\r\n  Each application form must be signed by the visa applicant personally. \r\n\r\n 2. Valid national passport (original only and it should have at least two clear visa pages). It must be valid no less than six months after the visa expiration date. Holders of travel documents such us: Permit to Re-Enter the United States of America, Travel Document, etc. must submit valid Permanent Resident Card (an original and a copy).
3. One picture of an applicant. Russian visa photo specifications. \r\n\r\n  4. Money Order or Certified Bank Check made out to the Russian Consulate for visa processing. Please note that we do not accept cash, credit or debit cards, personal or company checks. \r\n\r\n  5. Invitation to Russia from a host person or organisation. \r\n\r\n Dear Applicants, when applying for a Russian visa please be advised that \r\n\r\n • In order to expedite and improve visa obtaining process as well as for security concerns the Consular Division is no more processing visa applications by mail, starting from June 1, 2010. \r\n\r\n • Non-US citizens should also provide proof of legality of their stay in the USA (US Resident Alien status, form I-94) when applying for a visa. \r\n\r\n  • Applicants who used to be citizens of the USSR or the Russian Federation and emigrated from the USSR or from Russia must submit one of the documents which confirms that they are no longer citizens of the Russian Federation (so called 'Visa to Israel' or stamp in their passport saying that they left for 'permanent residence abroad' before February, 06 1992 or official document certifying that their Russian citizenship was renounced), otherwise the applications will not be accepted. \r\n\r\n • In accordance with Russian laws citizens of the Russian Federation regardless of any other citizenship theymay have, must travel to Russia on valid Russian documents only. \r\n\r\n • Please be advised that person can not have two valid visas in one passport. In this case the first visa is to be cancelled.")
